# Generated by Django 6.1 on 2026-08-21 09:20

import applications.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_job_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', validators=[applications.models.validate_resume_file])),
                ('resume_url', models.URLField(blank=True, default='', help_text='Optional external link to resume or portfolio (e.g. Google Drive, LinkedIn)', max_length=500)),
                ('cover_letter', models.TextField(blank=True, default='', help_text='Cover letter or note to the employer')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interview Scheduled / Interviewed'), ('offered', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Not Selected'), ('withdrawn', 'Withdrawn by Applicant')], default='pending', max_length=20)),
                ('company_notes', models.TextField(blank=True, default='', help_text='Private internal notes for the hiring team')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Candidate evaluation score (1-5)', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'), models.Index(fields=['applicant', '-applied_at'], name='job_applica_applica_e0dbab_idx'), models.Index(fields=['status'], name='job_applica_status_6d1402_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_application')],
            },
        ),
    ]
