# Generated by Django 6.1 on 2026-08-24 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(default='Software & SaaS', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_covers/%Y/%m/')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('product_url', models.URLField(blank=True, default='', max_length=400)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active / Available'), ('sold_out', 'Sold Out'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='jobs.product')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
