# Generated by Django 6.1 on 2026-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_product_productinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='sender_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
    ]
