# Generated by Django 6.1 on 2026-08-21 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_job_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('job', 'Job Posting'), ('user', 'User / Company Account')], default='job', max_length=20)),
                ('reason', models.CharField(choices=[('spam_or_scam', 'Spam, Fraud, or Scam'), ('fake_job', 'Fake or Misleading Job'), ('inappropriate_content', 'Inappropriate or Offensive Content'), ('harassment', 'Harassment or Threatening Behavior'), ('discrimination', 'Discriminatory Language or Practice'), ('impersonation', 'Impersonation or False Identity'), ('other', 'Other Issue')], default='spam_or_scam', max_length=40)),
                ('description', models.TextField(help_text='Detailed explanation of the issue')),
                ('evidence_url', models.URLField(blank=True, default='', help_text='Optional link to screenshot, document, or external evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Investigation'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed / No Violation')], default='pending', max_length=30)),
                ('action_taken', models.CharField(choices=[('none', 'No Action Yet'), ('job_removed', 'Job Removed / Closed'), ('user_warned', 'User Warned'), ('user_suspended', 'User Account Suspended'), ('dismissed', 'Report Dismissed')], default='none', max_length=30)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Super Admin resolution investigation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='jobs.job')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_status_d7deb7_idx'), models.Index(fields=['target_type', 'status'], name='reports_target__623377_idx'), models.Index(fields=['reporter', '-created_at'], name='reports_reporte_25ecfc_idx')],
            },
        ),
    ]
