# Generated by Django 6.1 on 2026-08-19 13:09

import django.core.validators
import user.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100, validators=[user.validators.validate_safe_input])),
                ('last_name', models.CharField(max_length=100, validators=[user.validators.validate_safe_input])),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[user.validators.validate_safe_input])),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('company', 'Company'), ('applicant', 'Applicant')], db_index=True, default='applicant', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), user.validators.FileValidator.validate_file_type])),
                ('about_you', models.TextField(blank=True, validators=[user.validators.validate_rich_text])),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, validators=[user.validators.validate_safe_input])),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), user.validators.FileValidator.validate_file_type])),
                ('company_description', models.TextField(blank=True, null=True, validators=[user.validators.validate_rich_text])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), user.validators.FileValidator.validate_file_type])),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email', 'role'], name='users_email_7645ab_idx'), models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'), models.Index(fields=['email_verification_token'], name='users_email_v_9c78de_idx')],
            },
        ),
    ]
